#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

export HIDE_WHOWHERE="vasili@hal"

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

unsetopt cdablevars
unsetopt AUTO_CD
setopt interactivecomments
HISTSIZE=100000
SAVEHIST=100000
HISTORY_SUBSTRING_SEARCH_HIGHLIGHT_FOUND=''

alias -g pacman=pacmatic
unalias du
setopt rm_star_silent
zstyle ':completion:*' rehash true

CUSTOM_JAVA_HOME="$HOME/code/java"
if [[ -d "$CUSTOM_JAVA_HOME" ]] && [[ -z "$JAVA_HOME" ]]; then
    export JAVA_HOME="$CUSTOM_JAVA_HOME"
fi

# add destination of symlinks in ~/.bin-dirs to PATH
if [[ -d ~/.bin-dirs ]]; then
    for dir in $(readlink -f ~/.bin-dirs/*); do
      PATH="$dir:$PATH"
    done
fi

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$SDKMAN_DIR/bin/sdkman-init.sh" ]] && source "$SDKMAN_DIR/bin/sdkman-init.sh"
