#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

export HIDE_WHOWHERE="vasili@hal"

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

unsetopt cdablevars
unsetopt AUTO_CD
setopt interactivecomments
HISTSIZE=100000
SAVEHIST=100000
HISTORY_SUBSTRING_SEARCH_HIGHLIGHT_FOUND=''

alias -g pacman=pacmatic
unalias du
setopt rm_star_silent
zstyle ':completion:*' rehash true
# allow > to truncate dest file (some scripts e.g. sdkman depend on this)
setopt clobber

# add destination of symlinks in ~/.bin-dirs to PATH
if [[ -d ~/.bin-dirs ]]; then
    for dir in $(readlink -f ~/.bin-dirs/*); do
      PATH="$dir:$PATH"
    done
fi
